---
version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/test-package:
          name: node-12
      - release-management/release-package:
          github-release: true
          requires:
            - node-latest
          filters:
            branches:
              only: main
